steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/amplified-land-478620-p4/fpl-service', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/amplified-land-478620-p4/fpl-service']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - fpl-service
      - --image=gcr.io/amplified-land-478620-p4/fpl-service
      - --region=europe-west1
      - --platform=managed
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 900s
